--1
CREATE DATABASE Test
GO
USE Test

CREATE TABLE Passports(
PassportID INT PRIMARY KEY IDENTITY(101,1),
PassportNumber NCHAR(8) NOT NULL
)

CREATE TABLE Persons(
PersonId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
Salary decimal(8,2) NOT NULL,
PassportID INT NOT NULL UNIQUE
CONSTRAINT FK_PassportID REFERENCES Passports(PassportID)
)

INSERT INTO Passports(PassportNumber)
VALUES
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2')


INSERT INTO Persons(FirstName,Salary,PassportID)
VALUES
('Roberto',43300.00,102),
('Tom' ,56100.00,103),
('Yana',60200.00,101)

SELECT * FROM Persons
SELECT * FROM Passports

--2
CREATE TABLE Manufacturers(
ManufacturerID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(20) NOT NULL,
EstablishedOn DATETIME NOT NULL
)

CREATE TABLE Models(
ModelID INT IDENTITY(101,1) PRIMARY KEY,
[Name] NVARCHAR(30) NOT NULL,
ManufacturerID INT FOREIGN KEY REFERENCES Manufacturers(ManufacturerID)
)

INSERT INTO Manufacturers([Name],EstablishedOn)
VALUES
('BMW','07/03/1916'),
('Tesla','01/01/2003'),
('Lada','01/05/1966')

INSERT INTO Models([Name],ManufacturerID)
VALUES
 ('X1',1),
 ('i6',1),
 ('Model S',2),
 ('Model X',2),
 ('Model 3',2),
 ('Nova',3)

 SELECT * FROM Manufacturers
 SELECT * FROM Models

 --3
 CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE Exams(
ExamID INT PRIMARY KEY IDENTITY(101,1),
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE StudentsExams(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
ExamID INT FOREIGN KEY REFERENCES Exams(ExamID),
CONSTRAINT PK_StudentExam PRIMARY KEY(StudentID,ExamID)
)

INSERT INTO Students([Name])
VALUES
('Mila'),
('Toni'),
('Ron')

INSERT INTO Exams([Name])
VALUES
('SpringMVC'),
('Neo4j'),
('Oracle 11g')

INSERT INTO StudentsExams(StudentID,ExamID)
VALUES 
(1,101),
(1,102),
(2,101),
(3,103),
(2,102),
(2,103)

--4
CREATE TABLE Teachers(
TeacherID INT NOT NULL PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
ManagerID INT NULL FOREIGN KEY REFERENCES Teachers(TeacherID)
)
--5
CREATE TABLE ItemTypes(
ItemTypeID INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Items(
ItemID INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Cities(
CityID INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers(
CustomerID INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
Birthday DATETIME2 NOT NULL,
CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
OrderID INT IDENTITY PRIMARY KEY,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
CONSTRAINT PK_OrderItem PRIMARY KEY(OrderID,ItemID)
)
--6
CREATE DATABASE Test2
GO
USE Test2
CREATE TABLE Majors(
MajorID INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL
)
CREATE TABLE Students(
StudentID INT IDENTITY PRIMARY KEY,
StudentNumber NCHAR(12) NOT NULL,
StudentName NVARCHAR(100) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)
CREATE TABLE Subjects(
SubjectID INT IDENTITY PRIMARY KEY,
[SubjectName] NVARCHAR(100) NOT NULL
)
CREATE TABLE Agenda(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)
CONSTRAINT PK_StudentSubject PRIMARY KEY (StudentID,SubjectID)
)
CREATE TABLE Payments(
PaymentID INT Primary KEY IDENTITY,
PaymentDate DATETIME2 NOT NULL,
PaymentAmount DECIMAL(7,2) NOT NULL,
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)
--9
USE Geography
SELECT * FROM Mountains
SELECT * FROM Peaks

SELECT m.MountainRange,p.PeakName,p.Elevation FROM Mountains AS m
JOIN Peaks AS p ON m.Id = p.MountainId
WHERE m.MountainRange = 'Rila'
ORDER BY Elevation DESC
